M48
; DRILL file {KiCad 9.0.4} date 2025-10-29T20:44:30-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-10-29T20:44:30-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
%
G90
G05
T1
X109.728Y-31.496
X143.002Y-31.496
T2
X113.465Y-86.0
M30
