M48
; DRILL file {KiCad 9.0.4} date 2025-12-11T20:36:51-0600
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-11T20:36:51-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
%
G90
G05
T1
X106.0Y-27.0
X106.0Y-100.0
X148.0Y-27.0
X148.0Y-100.0
T2
X110.132Y-90.147
M30
